### ISSUE TITLE
bug for increment?

### ISSUE THREAD

**Issue by toFrankie** [ChronVer/chronver#1]
Unexpected behavior occurs when using increment when the version number contains `Change` (such as `2020.03.16.4`).

Example as follow:

```js
import chronver from 'chronver'

const originalVersion = '2020.03.16.4'
const incrementList = ['change', 'day', 'month', 'year']

const newVersionList = incrementList.map(increment => {
  const chronverInst = new chronver.default({
    increment,
    version: originalVersion,
  })
  return `${originalVersion} -> ${chronverInst.version}`
})

console.log(newVersionList)
```

The result is correct only when increment is `change`.

```js
[
  '2020.03.16.4 -> 2020.03.16.5',
  '2020.03.16.4 -> 2020.03.05',
  '2020.03.16.4 -> 2020.05.16',
  '2020.03.16.4 -> 2023.10.09'
]
```

The expected result should be:

```js
[
  '2020.03.16.4 -> 2020.03.16.5', // change
  '2020.03.16.4 -> 2020.03.17', // day
  '2020.03.16.4 -> 2020.04.16', // month
  '2020.03.16.4 -> 2021.03.16' // year
]
```

Please take a look, thx.

**Comment by toFrankie** [comment]
`2023.12.31` increment to:

- `2023.12.32` (day)
- `2023.13.31` (month)

???

**Comment by NetOpWibby** [comment]
Hi @toFrankie, not sure why I'm _just_ now seeing this but I've rewritten this implementation so it should fix this issue. Let me know if your issue persists!
